# Generated by Django 5.0.8 on 2024-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('COMPLETED', 'Task Completed'), ('CREATER_CANCELLED', 'Task Cancelled by creater'), ('ASSIGNER_CANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned'), ('DETAILS_UPDATED', 'Details Updated'), ('REMINDER_24', '24 Hour Reminder'), ('REMINDER_1', '1 Hour Reminder')], max_length=20),
        ),
    ]
