services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: realstate_new_production_django
    volumes:
      - production_django_media:/app/realstate_new/media
      - ./logs:/app/logs  # Changed to relative path for easier permissions management
    user: django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    command: /start

  celeryworker:
    <<: *django
    image: realstate_new_production_celeryworker
    volumes:
      - production_django_media:/app/realstate_new/media
      - ./logs:/app/logs  # Changed to relative path
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: realstate_new_production_celerybeat
    volumes:
      - production_django_media:/app/realstate_new/media
      - ./logs:/app/logs  # Changed to relative path
    command: /start-celerybeat

  flower:
    <<: *django
    image: realstate_new_production_flower
    volumes:
      - production_django_media:/app/realstate_new/media
      - ./logs:/app/logs  # Changed to relative path
    command: /start-flower
