# Generated by Django 5.0.6 on 2024-07-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalPayementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transmission_id', models.CharField(max_length=255)),
                ('transmission_time', models.DateTimeField()),
                ('event_body', models.JSONField()),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
    ]
