# Generated by Django 5.0.7 on 2024-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paypalpayementhistory_transcation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpayementhistory',
            name='transmission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
