# Generated by Django 5.0.7 on 2024-08-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paypalpayementhistory_transmission_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
