# Generated by Django 5.0.8 on 2024-09-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayementhistory',
            name='payment_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paypalpayementhistory',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paypalpayementhistory',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payment.wallet'),
        ),
    ]
