# Generated by Django 5.0.8 on 2024-09-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paypalpayementhistory_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalpayementhistory',
            name='event_body',
        ),
        migrations.RemoveField(
            model_name='paypalpayementhistory',
            name='transmission_id',
        ),
        migrations.RemoveField(
            model_name='paypalpayementhistory',
            name='transmission_time',
        ),
        migrations.RemoveField(
            model_name='paypalpayementhistory',
            name='valid',
        ),
    ]
