# Generated by Django 5.0.8 on 2024-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_paypalpayementhistory_event_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayementhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paypalpayementhistory',
            name='transcation_type',
            field=models.CharField(choices=[('DIPOSIT', 'DIPOSIT'), ('WITHDRAW', 'WITHDRAW')], max_length=50),
        ),
    ]
