# Generated by Django 5.0.8 on 2024-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_paypalpayementhistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpayementhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
