# Generated by Django 5.0.8 on 2024-10-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0014_remove_paypalpayementhistory_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayementhistory',
            name='content_type',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paypalpayementhistory',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paypalpayementhistory',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paypalpayementhistory',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paypalpayementhistory',
            name='retry_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
