# Generated by Django 5.0.7 on 2024-11-01 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_remove_transcation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
