# Generated by Django 5.0.8 on 2024-11-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_stripetranscation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetranscation',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PROCESSING', 'PROCESSING'), ('INITIATED', 'INITIATED')], default='FAILED', max_length=255),
            preserve_default=False,
        ),
    ]
