# Generated by Django 5.0.8 on 2024-11-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_stripetranscation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetranscation',
            name='txn_type',
            field=models.CharField(choices=[('PAYIN', 'PAYIN'), ('PAYOUT', 'PAYOUT')], default='PAYIN', max_length=50),
        ),
        migrations.AlterField(
            model_name='stripetranscation',
            name='amt',
            field=models.PositiveIntegerField(),
        ),
    ]
