# Generated by Django 5.0.7 on 2024-08-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_address', models.TextField()),
                ('property_type', models.CharField(choices=[('SFH', 'Single Family Home'), ('CONDO', 'Condo'), ('APT', 'Apartment'), ('COMM', 'Commercial')], max_length=50)),
                ('listing_date', models.DateField()),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Under Contract', 'Under Contract'), ('Sold', 'Sold')], default='Available', max_length=50)),
                ('price', models.PositiveIntegerField(verbose_name='Current Listing Price')),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('lot_size', models.DecimalField(decimal_places=3, max_digits=5)),
                ('square_footage', models.DecimalField(decimal_places=3, max_digits=5)),
                ('year_built', models.PositiveIntegerField()),
                ('mls_number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(to='master.propertyfeature')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
