# Generated by Django 5.0.8 on 2024-09-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Status',
            new_name='status',
        ),
    ]
