# Generated by Django 5.0.8 on 2024-09-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_status_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='square_footage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
