# Generated by Django 5.0.7 on 2024-09-21 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_property_api_response_alter_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='api_response',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(null=True, to='master.propertyfeature'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 21, 6, 41, 19, 743509, tzinfo=datetime.timezone.utc)),
        ),
    ]
