# Generated by Django 5.0.7 on 2024-09-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_property_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='api_response',
            field=models.JSONField(default=dict),
        ),
    ]
