# Generated by Django 5.0.7 on 2024-09-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_property_api_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_address',
            new_name='delivery_line',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='listing_type',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='lot_size',
            new_name='lotsize_acres',
        ),
        migrations.RemoveField(
            model_name='property',
            name='api_response',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_footage',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='lotsize_sqft',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='zip',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
