# Generated by Django 5.0.7 on 2024-09-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_rename_property_address_property_delivery_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='delivery_line',
            field=models.CharField(default='', max_length=255),
        ),
    ]
