# Generated by Django 5.0.7 on 2024-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_property_delivery_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAIABLRE', 'Available'), ('UNDER CONTRACT', 'Under Contract'), ('SOLD', 'Sold'), ('OTHER', 'Other')], default='AVAIABLRE', max_length=50),
        ),
    ]
