# Generated by Django 5.0.8 on 2024-09-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lotsize_sqft',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
