# Generated by Django 5.0.8 on 2024-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_alter_property_lotsize_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lotsize_sqft',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
