# Generated by Django 5.0.8 on 2024-09-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_alter_property_lotsize_sqft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='listing_date',
        ),
    ]
