# Generated by Django 5.0.7 on 2024-09-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_alter_property_city_alter_property_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lotsize_acres',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lotsize_sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mls_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='year_built',
        ),
    ]
