# Generated by Django 5.0.8 on 2024-09-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_remove_property_description_remove_property_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='delivery_line',
        ),
    ]
