# Generated by Django 5.0.8 on 2024-10-11 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_remove_property_delivery_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['id'], name='master_prop_id_ffec41_idx'),
        ),
    ]
