# Generated by Django 5.0.8 on 2024-10-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_property_master_prop_id_ffec41_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='alarm_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='concierge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='gate_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD_ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
    ]
