# Generated by Django 5.0.8 on 2024-10-14 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('master', '0018_property_alarm_code_property_concierge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='property',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='concierge',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pets',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='vacant',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
