# Generated by Django 5.0.8 on 2024-10-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_alter_property_content_type_alter_property_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyFeature',
        ),
    ]
