# Generated by Django 5.0.8 on 2024-10-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_delete_propertyfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockbox_type', models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD_ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50)),
                ('lockbox_code', models.CharField(blank=True, default='', max_length=50)),
                ('additional_info', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='lockbox',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.lockbox'),
        ),
    ]
