# Generated by Django 5.0.8 on 2024-10-26 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_alter_professioanlvendorinquiry_additional_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='professioanlvendorinquiry',
            name='preferred_method_of_contact',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('EMAIL', 'EMAIL')], default='EMAIL'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField()),
                ('feedback_type', models.CharField(choices=[('BUG', 'Bug Report'), ('SUGGESTION', 'Suggestion'), ('GENERAL', 'General Feedback')], default='GENERAL', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
