# Generated by Django 5.0.8 on 2024-11-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_alter_professioanlvendorinquiry_service_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professioanlvendorinquiry',
            old_name='mile_radius_preference',
            new_name='area_covered',
        ),
    ]
