# Generated by Django 5.0.8 on 2024-12-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_rename_mile_radius_preference_professioanlvendorinquiry_area_covered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='lockbox_type',
        ),
    ]
