# Generated by Django 5.0.8 on 2024-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_payment_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
