# Generated by Django 5.0.8 on 2024-08-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(max_length=20),
        ),
    ]
