# Generated by Django 5.0.8 on 2024-08-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_alter_user_phone_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=20, unique=True),
        ),
    ]
