# Generated by Django 5.0.8 on 2024-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
