# Generated by Django 5.0.8 on 2024-09-06 07:04

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_phone_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EMAIL', 'EMAIL'), ('PHONE', 'PHONE'), ('WHATSAPP', 'WHATSAPP'), ('PUSH', 'PUSH')], default='EMAIL', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SHOWING', 'Showing'), ('OPEN_HOUSE', 'Open House'), ('LOCKBOX', 'Lockbox Install/Remove'), ('SIGN', 'Sign Install/Remove'), ('RUNNER', 'Runner Task'), ('PROFESSIONAL', 'Professional Services')], default='SHOWING', max_length=51),
        ),
    ]
