# Generated by Django 5.0.8 on 2024-09-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_notification_preference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notification_preference',
            new_name='notification_preferences',
        ),
    ]
