# Generated by Django 5.0.8 on 2024-09-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_notification_preference_user_notification_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_preferences',
        ),
        migrations.AddField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_notification',
            field=models.BooleanField(default=True),
        ),
    ]
