# Generated by Django 5.0.8 on 2024-09-09 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_educationdetail_professionaldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaldetail',
            name='duration',
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 17, 49, 4, 941315, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 17, 49, 17, 601864, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 17, 49, 29, 811439, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='skills',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionaldetail',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 17, 49, 53, 535967, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
