# Generated by Django 5.0.8 on 2024-09-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_professionaldetail_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='office_name',
            new_name='brokerage_name',
        ),
    ]
