# Generated by Django 5.0.8 on 2024-09-30 16:27

import realstate_new.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=realstate_new.users.models.upload_to),
        ),
    ]
