# Generated by Django 5.0.8 on 2024-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
    ]
