# Generated by Django 5.0.8 on 2024-10-04 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_fcmdevice_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcmdevices', to=settings.AUTH_USER_MODEL),
        ),
    ]
