# Generated by Django 5.0.8 on 2024-10-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_fcmdevice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='registration_id',
            field=models.TextField(),
        ),
    ]
