# Generated by Django 5.0.8 on 2024-10-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rating_rated_by_rating_rated_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_by',
        ),
    ]
