# Generated by Django 5.0.8 on 2024-10-10 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_rating_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
