# Generated by Django 5.0.8 on 2024-11-03 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_rating_rated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hyperwallet_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f75ed8d9-cc75-42ba-a632-e327e42b9970')),
        ),
    ]
