# Generated by Django 5.0.8 on 2024-11-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_charges_enabled',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_details_submitted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_payouts_enabled',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.TextField(default=''),
        ),
    ]
