# Generated by Django 5.0.8 on 2024-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_user_is_charges_enabled_user_is_details_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
