# Generated by Django 5.0.7 on 2024-11-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_user_is_charges_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_account_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
