# Generated by Django 5.0.6 on 2024-07-09 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['content_type', 'object_id'], name='application_content_5166a2_idx'),
        ),
    ]
