# Generated by Django 5.0.7 on 2024-08-04 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_jobapplication_applicant'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('object_id', 'content_type'), name='unique-application', violation_error_message='The record already exists.'),
        ),
    ]
