# Generated by Django 5.0.8 on 2024-09-27 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_jobapplication_status'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='application_content_5166a2_idx',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='object_id',
            new_name='task_id',
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['content_type', 'task_id'], name='application_content_9dbae3_idx'),
        ),
    ]
