# Generated by Django 5.0.8 on 2024-09-27 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_jobapplication_application_content_5166a2_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='unique-application',
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('task_id', 'content_type', 'applicant'), name='unique-application', violation_error_message='The record already exists.'),
        ),
    ]
