# Generated by Django 5.0.6 on 2024-07-12 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_lockboxtask_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockBoxTaskBS',
            fields=[
            ],
            options={
                'verbose_name': 'Lock Box (Buy / Sell)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('task.lockboxtask',),
        ),
        migrations.CreateModel(
            name='LockBoxTaskIR',
            fields=[
            ],
            options={
                'verbose_name': 'Lock Box (Install / Remove)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('task.lockboxtask',),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='dropoff_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='installation_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='installation_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='lockbox_collection_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='lockbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='show_client_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='sign_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='sign_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='show_client_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='show_client_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='show_client_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='show_client_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signtask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='signtask',
            name='show_client_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='payment_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='task_type',
            field=models.CharField(choices=[('install', 'Install'), ('remove', 'Remove'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=50),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='payment_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='payment_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='payment_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='payment_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='payment_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='task_type',
            field=models.CharField(choices=[('install', 'Install'), ('remove', 'Remove'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=50),
        ),
        migrations.CreateModel(
            name='LockBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('lockbox_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockbox', to='task.lockboxtask')),
            ],
        ),
    ]
