# Generated by Django 5.0.6 on 2024-07-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_lockboxtaskbs_lockboxtaskir_lockboxtask_brokerage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lockboxtaskir',
            options={'verbose_name': 'Lock Box (Install / Remove)', 'verbose_name_plural': 'Lock Box (Install / Remove)'},
        ),
        migrations.AlterField(
            model_name='lockbox',
            name='lockbox_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockbox', to='task.lockboxtaskbs'),
        ),
    ]
