# Generated by Django 5.0.6 on 2024-07-12 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_lockboxtaskir_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockbox',
            name='lockbox_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockbox', to='task.lockboxtaskbs', verbose_name='Lock Boxes'),
        ),
    ]
