# Generated by Django 5.0.6 on 2024-07-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_lockbox_lockbox_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='signtask',
            name='collection_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signtask',
            name='dropoff_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signtask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[("('SUPRA', 'SUPRA')", 'Supra'), ("('KEYPAD ENTRY', 'KEYPAD ENTRY')", 'Keypad Entry'), ("('CONTRACTOR', 'CONTRACTOR')", 'Contractor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='brokerage',
            field=models.CharField(choices=[("('MY-BROKERAGE', 'My Brokerage')", 'My Brokerage'), ("('OTHER-BROKERAGE', 'All Other Brokerages')", 'Other Brokerage')], default="('MY-BROKERAGE', 'My Brokerage')", max_length=50),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='lockbox_type',
            field=models.CharField(choices=[("('SUPRA', 'SUPRA')", 'Supra'), ("('KEYPAD ENTRY', 'KEYPAD ENTRY')", 'Keypad Entry'), ("('CONTRACTOR', 'CONTRACTOR')", 'Contractor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='brokerage',
            field=models.CharField(choices=[("('MY-BROKERAGE', 'My Brokerage')", 'My Brokerage'), ("('OTHER-BROKERAGE', 'All Other Brokerages')", 'Other Brokerage')], default="('MY-BROKERAGE', 'My Brokerage')", max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='brokerage',
            field=models.CharField(choices=[("('MY-BROKERAGE', 'My Brokerage')", 'My Brokerage'), ("('OTHER-BROKERAGE', 'All Other Brokerages')", 'Other Brokerage')], default="('MY-BROKERAGE', 'My Brokerage')", max_length=50),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='brokerage',
            field=models.CharField(choices=[("('MY-BROKERAGE', 'My Brokerage')", 'My Brokerage'), ("('OTHER-BROKERAGE', 'All Other Brokerages')", 'Other Brokerage')], default="('MY-BROKERAGE', 'My Brokerage')", max_length=50),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='brokerage',
            field=models.CharField(choices=[("('MY-BROKERAGE', 'My Brokerage')", 'My Brokerage'), ("('OTHER-BROKERAGE', 'All Other Brokerages')", 'Other Brokerage')], default="('MY-BROKERAGE', 'My Brokerage')", max_length=50),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='brokerage',
            field=models.CharField(choices=[("('MY-BROKERAGE', 'My Brokerage')", 'My Brokerage'), ("('OTHER-BROKERAGE', 'All Other Brokerages')", 'Other Brokerage')], default="('MY-BROKERAGE', 'My Brokerage')", max_length=50),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='task_type',
            field=models.CharField(choices=[('install', 'Install'), ('remove', 'Remove')], max_length=50),
        ),
    ]
