# Generated by Django 5.0.6 on 2024-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_signtask_collection_address_signtask_dropoff_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockboxtask',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'nnline'), ('OFFLINE', 'Offline'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT CARD', 'Credit Card'), ('BANK TRANSFER', 'Bank Transfer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='task_type',
            field=models.CharField(choices=[('INSTALL', 'Install'), ('REMOVE', 'Remove'), ('BUY', 'Buy'), ('SELL', 'Sell')], max_length=50),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'nnline'), ('OFFLINE', 'Offline'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT CARD', 'Credit Card'), ('BANK TRANSFER', 'Bank Transfer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'nnline'), ('OFFLINE', 'Offline'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT CARD', 'Credit Card'), ('BANK TRANSFER', 'Bank Transfer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'nnline'), ('OFFLINE', 'Offline'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT CARD', 'Credit Card'), ('BANK TRANSFER', 'Bank Transfer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='task_type',
            field=models.CharField(choices=[('DOCUMENT DELIVERY', 'Document Delivery'), ('KEY DROP OFF', 'Key Drop Off'), ('KEY PICK OFF', 'Key Pick Off'), ('PROPERTY CHECK', 'Property Check'), ('OTHER', 'Other'), ('MEET DELIVERY VENDOR', 'Meet delivery or Vendor'), ('ATTEND CLOSING', 'Attend closing for agent'), ('TAKE PHOTOS', 'Take photos of Inside / Outside of house, separate from professional photos'), ('PAPERWORK', 'Paperwork Courier / Paperwork in Office')], max_length=50),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'nnline'), ('OFFLINE', 'Offline'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT CARD', 'Credit Card'), ('BANK TRANSFER', 'Bank Transfer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'nnline'), ('OFFLINE', 'Offline'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT CARD', 'Credit Card'), ('BANK TRANSFER', 'Bank Transfer')], max_length=255),
        ),
    ]
