# Generated by Django 5.0.6 on 2024-07-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_lockboxtask_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnertask',
            name='closing_location_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runnertask',
            name='dropoff_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runnertask',
            name='pickup_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runnertask',
            name='vebdor_notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runnertask',
            name='vendor_company_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runnertask',
            name='vendor_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runnertask',
            name='vendor_phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
