# Generated by Django 5.0.6 on 2024-07-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_runnertask_closing_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockboxtask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='lockbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='brokerage',
            field=models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR')], max_length=50, null=True),
        ),
    ]
