# Generated by Django 5.0.6 on 2024-07-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('task', '0010_alter_lockboxtask_brokerage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockboxtask',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='openhousetask',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='professionalservicetask',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='showingtask',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='signtask',
            name='property_address',
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.property'),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.property'),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.property'),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.property'),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.property'),
        ),
        migrations.AddField(
            model_name='signtask',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.property'),
        ),
    ]
