# Generated by Django 5.0.6 on 2024-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_remove_lockboxtask_property_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveIntegerField()),
                ('request_body', models.TextField()),
                ('response_body', models.TextField()),
                ('endpoint', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
