# Generated by Django 5.0.6 on 2024-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_thirdpartycall_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartycall',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
