# Generated by Django 5.0.6 on 2024-08-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_lockboxtask_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockboxtask',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='openhousetask',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='professionalservicetask',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='showingtask',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='signtask',
            name='payment_method',
        ),
    ]
