# Generated by Django 5.0.7 on 2024-08-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_remove_lockboxtask_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockboxtask',
            name='dropoff_address',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='installation_address',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='installation_location',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='lockbox_collection_address',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='lockbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='pickup_address',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='sign_address',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signtask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
