# Generated by Django 5.0.8 on 2024-09-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_lockboxtask_dropoff_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartycall',
            name='request_body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='thirdpartycall',
            name='response_body',
            field=models.TextField(default=''),
        ),
    ]
