# Generated by Django 5.0.8 on 2024-09-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_alter_thirdpartycall_request_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockbox',
            old_name='type',
            new_name='lockbox_type',
        ),
    ]
