# Generated by Django 5.0.8 on 2024-09-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_alter_lockbox_lockbox_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalservicetask',
            name='service_type',
            field=models.CharField(choices=[('PHOTOGRAPHY', 'Photography'), ('CLEANING', 'Cleaning'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection'), ('OTHER', 'other'), ('HOME STAGING', 'Home Staging')], max_length=50),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='task_type',
            field=models.CharField(choices=[('INSTALL', 'Install'), ('REMOVE', 'Remove')], max_length=50),
        ),
    ]
