# Generated by Django 5.0.7 on 2024-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_alter_professionalservicetask_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signtask',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
