# Generated by Django 5.0.8 on 2024-09-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_lockboxtask_title_openhousetask_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockboxtask',
            old_name='show_client_phone_number',
            new_name='show_client_info',
        ),
        migrations.RenameField(
            model_name='openhousetask',
            old_name='show_client_phone_number',
            new_name='show_client_info',
        ),
        migrations.RenameField(
            model_name='professionalservicetask',
            old_name='show_client_phone_number',
            new_name='show_client_info',
        ),
        migrations.RenameField(
            model_name='runnertask',
            old_name='show_client_phone_number',
            new_name='show_client_info',
        ),
        migrations.RenameField(
            model_name='showingtask',
            old_name='show_client_phone_number',
            new_name='show_client_info',
        ),
        migrations.RenameField(
            model_name='signtask',
            old_name='show_client_phone_number',
            new_name='show_client_info',
        ),
        migrations.RemoveField(
            model_name='lockboxtask',
            name='job_deadline',
        ),
        migrations.RemoveField(
            model_name='openhousetask',
            name='job_deadline',
        ),
        migrations.RemoveField(
            model_name='professionalservicetask',
            name='job_deadline',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='job_deadline',
        ),
        migrations.RemoveField(
            model_name='showingtask',
            name='job_deadline',
        ),
        migrations.RemoveField(
            model_name='signtask',
            name='job_deadline',
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
