# Generated by Django 5.0.8 on 2024-09-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_rename_show_client_phone_number_lockboxtask_show_client_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='alarm_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='concierge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='gate_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='locbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='alarm_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='concierge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='gate_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='locbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='alarm_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='concierge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='gate_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='locbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='alarm_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='concierge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='gate_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='locbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='alarm_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='concierge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='gate_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='locbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signtask',
            name='alarm_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signtask',
            name='concierge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signtask',
            name='gate_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signtask',
            name='locbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='signtask',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signtask',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='lockbox_type',
            field=models.CharField(choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
