# Generated by Django 5.0.8 on 2024-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_rename_locbox_type_openhousetask_lockbox_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runnertask',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='lockboxtask',
            name='include_sign',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
