# Generated by Django 5.0.8 on 2024-09-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_alter_lockboxtask_alarm_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='asap',
            field=models.BooleanField(blank=True, null=True, verbose_name='As Soon As Possible'),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='asap',
            field=models.BooleanField(blank=True, null=True, verbose_name='As Soon As Possible'),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='asap',
            field=models.BooleanField(blank=True, null=True, verbose_name='As Soon As Possible'),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='asap',
            field=models.BooleanField(blank=True, null=True, verbose_name='As Soon As Possible'),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='asap',
            field=models.BooleanField(blank=True, null=True, verbose_name='As Soon As Possible'),
        ),
        migrations.AddField(
            model_name='signtask',
            name='asap',
            field=models.BooleanField(blank=True, null=True, verbose_name='As Soon As Possible'),
        ),
    ]
