# Generated by Django 5.0.8 on 2024-09-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0031_lockboxtask_asap_openhousetask_asap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhousetask',
            name='hosting_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='listing_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
