# Generated by Django 5.0.8 on 2024-09-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_alter_openhousetask_hosting_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockboxtask',
            old_name='dropoff_address',
            new_name='installation_or_remove_address',
        ),
        migrations.RemoveField(
            model_name='lockboxtask',
            name='installation_address',
        ),
        migrations.RemoveField(
            model_name='lockboxtask',
            name='installation_location',
        ),
        migrations.RemoveField(
            model_name='lockboxtask',
            name='lockbox_collection_address',
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='include_sign',
            field=models.BooleanField(blank=True, null=True, verbose_name='Include Install/Remove Sign'),
        ),
    ]
