# Generated by Django 5.0.8 on 2024-09-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0034_rename_dropoff_address_lockboxtask_installation_or_remove_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockboxtask',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lockboxtask',
            name='sign_address',
        ),
        migrations.RemoveField(
            model_name='lockboxtask',
            name='sign_option',
        ),
    ]
