# Generated by Django 5.0.8 on 2024-09-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0035_remove_lockboxtask_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockboxtask',
            name='installation_or_remove_address',
        ),
        migrations.RemoveField(
            model_name='lockboxtask',
            name='pickup_address',
        ),
    ]
