# Generated by Django 5.0.8 on 2024-09-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0037_lockboxtask_installation_or_remove_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='remove_sign',
            field=models.BooleanField(blank=True, null=True, verbose_name='Include Sign'),
        ),
        migrations.AlterField(
            model_name='lockboxtask',
            name='include_sign',
            field=models.BooleanField(blank=True, null=True, verbose_name='Include Sign'),
        ),
    ]
