# Generated by Django 5.0.8 on 2024-09-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0038_lockboxtask_remove_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhousetask',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
