# Generated by Django 5.0.8 on 2024-09-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0039_openhousetask_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runnertask',
            name='closing_location_address',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='pickup_address',
        ),
    ]
