# Generated by Django 5.0.8 on 2024-09-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_remove_property_listing_date'),
        ('task', '0040_remove_runnertask_closing_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnertask',
            name='dropoff_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.property'),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='pickup_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.property'),
        ),
    ]
