# Generated by Django 5.0.8 on 2024-09-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0042_alter_runnertask_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runnertask',
            name='vebdor_notes',
        ),
        migrations.AddField(
            model_name='runnertask',
            name='vendor_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='vendor_company_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='vendor_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
