# Generated by Django 5.0.8 on 2024-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0044_remove_signtask_collection_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signtask',
            name='sign_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
