# Generated by Django 5.0.8 on 2024-09-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0045_alter_signtask_sign_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signtask',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
