# Generated by Django 5.0.8 on 2024-09-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0046_alter_signtask_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockboxtask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD_ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD_ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD_ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD_ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD_ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD_ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
    ]
