# Generated by Django 5.0.8 on 2024-09-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0047_alter_lockboxtask_lockbox_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockboxtask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='openhousetask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='professionalservicetask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='showingtask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='signtask',
            name='title',
        ),
    ]
