# Generated by Django 5.0.8 on 2024-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0048_remove_lockboxtask_title_remove_openhousetask_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnertask',
            name='task_type',
            field=models.CharField(choices=[('ATTEND_CLOSING', 'Attend closing for agent'), ('PAPERWORK', 'Paperwork Courier / Paperwork in Office'), ('DOCUMENT_DELIVERY', 'Document Delivery'), ('NOTARY_SERVICE', 'Notary Services'), ('PROPERTY_INSPECTION', 'Property Inspections'), ('TRANSLATOR', 'Translator for secondary Language'), ('HOME_ERRANDS', 'Homes errands'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
