# Generated by Django 5.0.8 on 2024-09-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0049_alter_runnertask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockboxtask',
            name='lockbox_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
