# Generated by Django 5.0.8 on 2024-09-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0050_alter_lockboxtask_lockbox_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockboxtask',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
