# Generated by Django 5.0.8 on 2024-10-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0052_lockboxtask_title_openhousetask_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='not_acceptance_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='not_acceptance_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='not_acceptance_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='not_acceptance_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='not_acceptance_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signtask',
            name='not_acceptance_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
