# Generated by Django 5.0.8 on 2024-10-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0054_taskhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='user',
        ),
    ]
