# Generated by Django 5.0.8 on 2024-10-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0055_remove_taskhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('COMPLETED', 'Task Completed'), ('CREATER-CANCELLED', 'Task Cancelled by creater'), ('ASSIGNERCANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned')], max_length=20),
        ),
    ]
