# Generated by Django 5.0.8 on 2024-10-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0057_alter_taskhistory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('COMPLETED', 'Task Completed'), ('CREATER_CANCELLED', 'Task Cancelled by creater'), ('ASSIGNER_CANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned')], max_length=20),
        ),
    ]
