# Generated by Django 5.0.8 on 2024-10-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0058_alter_taskhistory_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
