# Generated by Django 5.0.8 on 2024-10-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0059_delete_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signtask',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
