# Generated by Django 5.0.8 on 2024-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0060_lockboxtask_is_cancelled_openhousetask_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='mark_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='mark_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='mark_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='mark_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='mark_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signtask',
            name='mark_completed',
            field=models.BooleanField(default=False),
        ),
    ]
