# Generated by Django 5.0.8 on 2024-10-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0061_lockboxtask_mark_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockboxtask',
            old_name='is_completed',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='lockboxtask',
            old_name='mark_completed',
            new_name='marked_completed_by_assignee',
        ),
        migrations.RenameField(
            model_name='openhousetask',
            old_name='is_completed',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='openhousetask',
            old_name='mark_completed',
            new_name='marked_completed_by_assignee',
        ),
        migrations.RenameField(
            model_name='professionalservicetask',
            old_name='is_completed',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='professionalservicetask',
            old_name='mark_completed',
            new_name='marked_completed_by_assignee',
        ),
        migrations.RenameField(
            model_name='runnertask',
            old_name='is_completed',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='runnertask',
            old_name='mark_completed',
            new_name='marked_completed_by_assignee',
        ),
        migrations.RenameField(
            model_name='showingtask',
            old_name='is_completed',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='showingtask',
            old_name='mark_completed',
            new_name='marked_completed_by_assignee',
        ),
        migrations.RenameField(
            model_name='signtask',
            old_name='is_completed',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='signtask',
            old_name='mark_completed',
            new_name='marked_completed_by_assignee',
        ),
    ]
