# Generated by Django 5.0.8 on 2024-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0062_rename_is_completed_lockboxtask_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='additional-audio-notes/'),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='additional-audio-notes/'),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='additional-audio-notes/'),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='additional-audio-notes/'),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='additional-audio-notes/'),
        ),
        migrations.AddField(
            model_name='signtask',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='additional-audio-notes/'),
        ),
    ]
