# Generated by Django 5.0.7 on 2024-10-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0064_alter_lockboxtask_asap_alter_openhousetask_asap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('VERIFIED', 'Task Verified'), ('CREATER_CANCELLED', 'Task Cancelled by creater'), ('ASSIGNER_CANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned'), ('MARK_COMPLETED', 'Task Marked Completed')], default='CREATED', max_length=50),
        ),
        migrations.AddField(
            model_name='openhousetask',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('VERIFIED', 'Task Verified'), ('CREATER_CANCELLED', 'Task Cancelled by creater'), ('ASSIGNER_CANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned'), ('MARK_COMPLETED', 'Task Marked Completed')], default='CREATED', max_length=50),
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('VERIFIED', 'Task Verified'), ('CREATER_CANCELLED', 'Task Cancelled by creater'), ('ASSIGNER_CANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned'), ('MARK_COMPLETED', 'Task Marked Completed')], default='CREATED', max_length=50),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('VERIFIED', 'Task Verified'), ('CREATER_CANCELLED', 'Task Cancelled by creater'), ('ASSIGNER_CANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned'), ('MARK_COMPLETED', 'Task Marked Completed')], default='CREATED', max_length=50),
        ),
        migrations.AddField(
            model_name='showingtask',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('VERIFIED', 'Task Verified'), ('CREATER_CANCELLED', 'Task Cancelled by creater'), ('ASSIGNER_CANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned'), ('MARK_COMPLETED', 'Task Marked Completed')], default='CREATED', max_length=50),
        ),
        migrations.AddField(
            model_name='signtask',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('VERIFIED', 'Task Verified'), ('CREATER_CANCELLED', 'Task Cancelled by creater'), ('ASSIGNER_CANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned'), ('MARK_COMPLETED', 'Task Marked Completed')], default='CREATED', max_length=50),
        ),
    ]
