# Generated by Django 5.0.8 on 2024-10-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0065_lockboxtask_status_openhousetask_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signtask',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='signtask',
            name='install_address',
        ),
        migrations.RemoveField(
            model_name='signtask',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='signtask',
            name='remove_address',
        ),
    ]
