# Generated by Django 5.0.8 on 2024-10-13 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_property_master_prop_id_ffec41_idx'),
        ('task', '0066_remove_signtask_dropoff_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signtask',
            name='installation_or_remove_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.property'),
        ),
    ]
