# Generated by Django 5.0.8 on 2024-10-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0067_signtask_installation_or_remove_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockboxtask',
            old_name='job_type',
            new_name='application_type',
        ),
        migrations.RenameField(
            model_name='openhousetask',
            old_name='job_type',
            new_name='application_type',
        ),
        migrations.RenameField(
            model_name='professionalservicetask',
            old_name='job_type',
            new_name='application_type',
        ),
        migrations.RenameField(
            model_name='runnertask',
            old_name='job_type',
            new_name='application_type',
        ),
        migrations.RenameField(
            model_name='showingtask',
            old_name='job_type',
            new_name='application_type',
        ),
        migrations.RenameField(
            model_name='signtask',
            old_name='job_type',
            new_name='application_type',
        ),
    ]
