# Generated by Django 5.0.8 on 2024-10-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0068_rename_job_type_lockboxtask_application_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalservicetask',
            old_name='service_instructions',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='professionalservicetask',
            old_name='service_provider_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='professionalservicetask',
            old_name='service_provider_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='professionalservicetask',
            old_name='service_provider_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='lockboxtask',
            name='instructions',
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionalservicetask',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
