# Generated by Django 5.0.8 on 2024-10-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_property_master_prop_id_ffec41_idx'),
        ('task', '0069_rename_service_instructions_professionalservicetask_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signtask',
            old_name='installation_or_remove_address',
            new_name='dropoff_address',
        ),
        migrations.AddField(
            model_name='signtask',
            name='install_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.property'),
        ),
        migrations.AddField(
            model_name='signtask',
            name='pickup_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.property'),
        ),
        migrations.AddField(
            model_name='signtask',
            name='remove_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.property'),
        ),
    ]
