# Generated by Django 5.0.8 on 2024-10-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0072_lockboxtask_client_email_lockboxtask_client_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockboxtask',
            name='property',
        ),
        migrations.RemoveField(
            model_name='openhousetask',
            name='property',
        ),
        migrations.RemoveField(
            model_name='professionalservicetask',
            name='property',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='property',
        ),
        migrations.RemoveField(
            model_name='showingtask',
            name='property',
        ),
        migrations.RemoveField(
            model_name='signtask',
            name='property',
        ),
        migrations.DeleteModel(
            name='LockBox',
        ),
    ]
