# Generated by Django 5.0.8 on 2024-10-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0073_remove_lockboxtask_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockboxtask',
            name='lockbox_type',
            field=models.CharField(blank=True, choices=[('SUPRA', 'SUPRA'), ('KEYPAD_ENTRY', 'KEYPAD ENTRY'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=50),
        ),
    ]
