# Generated by Django 5.0.8 on 2024-10-14 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_delete_propertyfeature'),
        ('task', '0074_lockboxtask_lockbox_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhousetask',
            name='property_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.property'),
            preserve_default=False,
        ),
    ]
