# Generated by Django 5.0.8 on 2024-10-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_delete_propertyfeature'),
        ('task', '0075_openhousetask_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhousetask',
            name='property_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.property'),
        ),
    ]
