# Generated by Django 5.0.8 on 2024-10-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0076_alter_openhousetask_property_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runnertask',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='vendor_company_name',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='vendor_name',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='vendor_notes',
        ),
        migrations.RemoveField(
            model_name='runnertask',
            name='vendor_phone',
        ),
    ]
