# Generated by Django 5.0.8 on 2024-10-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_delete_propertyfeature'),
        ('task', '0078_runnertask_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservicetask',
            name='property_address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.property'),
            preserve_default=False,
        ),
    ]
