# Generated by Django 5.0.8 on 2024-10-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0079_professionalservicetask_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnertask',
            name='vendor_company_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='vendor_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='runnertask',
            name='vendor_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
