# Generated by Django 5.0.8 on 2024-11-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0083_lockboxtask_payment_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockboxtask',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
