# Generated by Django 5.0.8 on 2024-11-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0084_alter_lockboxtask_payment_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockboxtask',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='openhousetask',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='professionalservicetask',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='runnertask',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='showingtask',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
