# Generated by Django 5.0.8 on 2024-11-14 09:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_alter_professioanlvendorinquiry_service_skill'),
        ('task', '0085_alter_lockboxtask_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OpenForVendorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=50)),
                ('client_phone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('client_email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None)),
                ('task_time', models.DateTimeField()),
                ('asap', models.BooleanField(default=False, verbose_name='As Soon As Possible')),
                ('notes', models.TextField(blank=True, default='')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('application_type', models.CharField(choices=[('APPLY', 'Apply'), ('CLAIM', 'Claim')], default='APPLY', max_length=5)),
                ('apply_deadline', models.DateTimeField(blank=True, null=True)),
                ('brokerage', models.CharField(choices=[('MY-BROKERAGE', 'My Brokerage'), ('OTHER-BROKERAGE', 'All Other Brokerages')], default='MY-BROKERAGE', max_length=50)),
                ('show_client_info', models.BooleanField(default=False)),
                ('not_acceptance_notification_sent', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('marked_completed_by_assignee', models.BooleanField(default=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='additional-audio-notes/')),
                ('status', models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Task Assigned'), ('STARTED', 'Task Started'), ('VERIFIED', 'Task Verified'), ('CREATER_CANCELLED', 'Task Cancelled by creater'), ('ASSIGNER_CANCELLED', 'Task Cancelled by assigner'), ('REASSIGNED', 'Task Reassigned'), ('MARK_COMPLETED', 'Task Marked Completed')], default='CREATED', max_length=50)),
                ('payment_verified', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('property_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.property')),
                ('open_for_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.vendortype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
