# Generated by Django 5.0.8 on 2024-11-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0086_vendortype_openforvendortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='openforvendortask',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='openforvendortask',
            name='vendor_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
