# Generated by Django 5.0.8 on 2024-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0087_openforvendortask_vendor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openforvendortask',
            name='property_address',
        ),
        migrations.AddField(
            model_name='openforvendortask',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
