# Generated by Django 5.0.8 on 2024-11-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0088_remove_openforvendortask_property_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openforvendortask',
            name='open_for_vendor',
        ),
    ]
