# Generated by Django 5.0.8 on 2024-11-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0089_remove_openforvendortask_open_for_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='openforvendortask',
            name='open_for_vendor',
            field=models.ManyToManyField(blank=True, null=True, to='task.vendortype'),
        ),
    ]
