# Generated by Django 5.0.8 on 2024-12-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0090_openforvendortask_open_for_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockboxtask',
            name='lockbox_code',
        ),
        migrations.RemoveField(
            model_name='lockboxtask',
            name='lockbox_type',
        ),
    ]
